### ISSUE TITLE
Create Init Function

### ISSUE THREAD

**Issue by gwolf-011235** [gwolf-011235/minishell#1]
When starting the shell, it should initialize its environment. 

- This will probably be implemented with the environment pointer char **envp, so that the main function looks like main(int argc, char **argv, char **envp)
- Alternative is then environ variable - which would be our first global

The following situations should be handled:

1. There was an environment --> copy it
2. There was no environment --> what then? (what is when home is not set?)

**Comment by gwolf-011235** [comment]
Not closed!

**Comment by u413-284-si** [comment]
branch was rebased unto main with 0 conflicts
