### ISSUE TITLE
Makefile is sometimes strange

### ISSUE THREAD

**Issue by gwolf-011235** [gwolf-011235/minishell#18]
Today Makefile was recompiling every time. I think it has something to do with dependency generation. Couldn't find out what was wrong; now it works again

**Comment by u413-284-si** [comment]
What? 😂

Shouldn't this be connected with the rule which is called by make and whether or not it finds the corresponding target in the dir, e.g. make calls 'all'. 'all' has the target 'minishell' and if there is already an executable named minishell present in the dir, make will stop.

**Comment by gwolf-011235** [comment]
Yeah that would be nice :D I can't reproduce it right now, but when I ran make several times it always recompiled (even though nothing had changed). 

I think the problem are the dependency files: if they are newer than the object files, the object files get recreated which also recreates the dependency files resulting in a loop. (this is also mentioned in the link explaining the dependency generation). But: then it should always happen and right now everything seems fine.

If we are scared we could remove the dependencies but I would leave them for now :dancing_women: 

Also: for the dependencies to work we shouldn't use one big header file. Then the dependencies are not as effective since a change in the big header would result in recompilation of all objects (since they all depend on it). Ima try to split these up.

**Comment by gwolf-011235** [comment]
I might have something to do with the compiler verison used at school. New clang has no problems but maybe school doesn't get it.
