### ISSUE TITLE
Tokenise does not work without newline

### ISSUE THREAD

**Issue by gwolf-011235** [gwolf-011235/minishell#31]
If there isn't any newline in the input string ft_list_token() exits out of the while loop, before saving the last filled buffer, since it received ERR_EOF.

Testcase: "~ $TEST" (without newline)
Expected: two tokens "\~" and "$TEST" 
Result: one token "~"

Should be handled since readline removes the last newline of the input string. So it's standard, that a command has no newline at the end.

I think check for '\0' but then just break out and don't ft_unget_char?

**Comment by u413-284-si** [comment]
Issue has been addressed with latest changes/commits to branch 29. Last token is saved into the list even without newline
