### ISSUE TITLE
Change Lexing sequence

### ISSUE THREAD

**Issue by gwolf-011235** [gwolf-011235/minishell#35]
Right now the input string gets
1. tokenized
2. expanded + quote removed

This can lead to a bug, if the expanded variable is a command + arg, e.g. test="ls -la". 
In this case the tokenizer doesn't recognize the token, since it's not expanded yet. This is a problem for execve, which needs it's args neatly cut.

Simply swapping tokenize and expand+quotes also doesn't work. It could cut up a previously quoted string.

A possible solution could be expand > tokenize > quote removal. Therefore expand+quotes function needs to be split.

**Comment by gwolf-011235** [comment]
It seems like the better solution would be to implement word splitting (see bash manual 3.5.7).

A result of parameter expansion that did not occur within double quotes is scanned for word splitting.

I think a very rudimentary version (no changeable delimiter $IFS variable) should be sufficient.

One word can become two or more after splitting. Therefore the input params of the expand function need to be adapted. Tkn_lst could be a good choice.

**Comment by gwolf-011235** [comment]
If a redirection filename gets expanded and Field splitting would create two or more tokens bash writes an error saying ambiguous redirect and doesn't execute. 

However a pipe gets executed and only stops at ambiguous redirect. Could be implemented while parsing and setting out or in_fd to a special value.

**Comment by gwolf-011235** [comment]
Similar problem as last comment: if the file name gets expanded to nothing then it's also ambiguous redirect.

However if the filename is a not existing var which is quoted (e.g. "$NO_EXIST") it's a file does not exist error

Maybe make special type in t_type and flag in t_cmd for ambiguous redirect

**Comment by u413-284-si** [comment]
Need to elaborate on the non-existing filename case

**Comment by gwolf-011235** [comment]
In case of environment variable ARG not defined:

- If you do < "$ARG" then $ARG will be expanded to nothing. So the remaining string is "" (Two quotes). The quotes get removed by the quote-remover, leaving an empty string behind. This is then tried to be opened (which fails because there is not file with no name - I don't think there can be?)
- However < $ARG behaves a bit differently: $ARG will also get expanded to nothing but there are not quotes. So the string is already an empty string. I think in this case the empty string gets removed by bash. The returned error is ambiguous redirect (because there is no filename)

The removal of 'true' empty strings (which are empty before quote removal - don't have a better name for them :D ) is also indicated by these to echo commands:
- `echo hello "$ARG" world`
- `echo hello $ARG world`

The first one prints two spaces (string doesn't get removed). The second one prints only one.

**Comment by gwolf-011235** [comment]
Turns out: bash --posix does it yet another way.

- field split args
- don't field split redirection file names

This means 
`ARG="this is file"`
`echo hi > $ARG`
creates a outfile named "this is file" (with spaces)

This only leaves one case of error of "ambiguous redirect": if expansion creates a unquoted empty string

**Comment by u413-284-si** [comment]
Can you summarise the behaviour of expanding in bash --posix? I think we will both benefit, if we have a list of cases with examples that shows what kind of behaviour we need to considerate in the implementation.

**Comment by gwolf-011235** [comment]
I'll try :D

Under the term **expansion** fall different string manipulations. Depending on the type of token one or more are applied. The ones, which we have to implement are:

1. Tilde expansion: if a tilde (~) is at the start of a token or after an assignment in a token expand it to the path of the home directory
2. Variable (or Parameter) expansion: if a $ is encountered, it may be a variable. It has to start with an alphabetic character or underscore. After the first char numbers are allowed additionally. Replace the variable name with the value of the environment
3. Field splitting: after an variable expansion occured and the token was unqoted, split the result delimited by spaces/tab/newline. Explicit null arguments ( "" ) are retained as empty strings, implicit (e.g. a var expands to nothing) are removed.
4. Quote removal: remove single and double quotes except if they are themselves quoted.

Not all expansions are always performed. It depends on the type of token. They are also only performed once (it doesn't get repeated until no expansion is possible anymore). Using our t_type:

- ARG: 1, 2, 3, 4
- HEREDOC: 4.
- INFILE, OUTFILE, APPEND: 1, 2, 4 (debatable: Bash manual 3.6 says field splitting yes, but bash --posix clearly does not)
- (Not yet implemented) ASSIGN: in an variable assignment (test=$arg): 1, 2, 4

I will split the current expand function, which right now (always) does 1, 2, 4 into three separate functions and implement a field splitting function. Then a driver function which, depending on the t_type, does one or more of the expansions.
