### ISSUE TITLE
Make 42ready before push

### ISSUE THREAD

**Issue by gwolf-011235** [gwolf-011235/minishell#44]
Before we push to the school repo we should do a final cleanup (This issue may need to be amended)

Files / directories to be removed:

- [x] README.md
- [x] Licence
- [x] .gitmodules
- [x] Directory tests
- [x] Directory docs
- [x] Directory .vscode
- [x] Directory .github
- [x] file minishell.supp

Cleanup in Makefile:

- [x] Remove TEST_DIR
- [x] Remove TEST
- [x] Add main.c to SRC
- [x] Remove OBJ_MAIN
- [x] Remove DEPFILES += main.d
- [x] Remove * Test files *
- [x] Remove * TEST linkage *
- [x] Remove target to create test object files
- [x] Remove target tclean

**Comment by gwolf-011235** [comment]
Renamed to avoid confusion with cleanup in programm

**Comment by u413-284-si** [comment]
Eval successfully completed

**Comment by u413-284-si** [comment]
Eval successfully completed
